name: Fetch Projects

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Fetch Projects
        run: node scripts/projectsFetcher.js

      - name: Commit JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/projects

          if git diff --cached --quiet; then
            echo "No Changes"
          else
            git commit -m "Fetch Projects"
            git push
          fi
